#!/usr/bin/env python3
# COPYRIGHT (C) 2022 Pavel Artsishevsky <polter.rnd@gmail.com>
#
# GNU GENERAL PUBLIC LICENSE
#    Version 3, 29 June 2007
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# pylint: disable=invalid-name,import-outside-toplevel

"""Executable script for running bbswitch-gui tool."""

import importlib.util
import sys


def load_module():
    """Check if bbswitch_gui module installed and load it."""
    if not importlib.util.find_spec("bbswitch_gui"):
        print("""Cannot find the bbswitch_gui module.
Perhaps it is installed in a folder which is not in Python's module search
path. There could be a version mismatch between the Python version that was
used to build the application binary package and the version you try to run
the application with.""")
        return 1

    from bbswitch_gui.application import Application
    return Application().run(sys.argv)


if __name__ == '__main__':
    sys.exit(load_module())
